DROP TABLE IF EXISTS LIGA CASCADE;
DROP TABLE IF EXISTS TIM CASCADE;
DROP TABLE IF EXISTS NACIONALNOST CASCADE;
DROP TABLE IF EXISTS IGRAC CASCADE;

DROP SEQUENCE IF EXISTS LIGA_SEQ;
DROP SEQUENCE IF EXISTS TIM_SEQ;
DROP SEQUENCE IF EXISTS NACIONALNOST_SEQ;
DROP SEQUENCE IF EXISTS IGRAC_SEQ;

CREATE TABLE LIGA(
	id INTEGER NOT NULL,
	naziv VARCHAR(100) NOT NULL,
	oznaka VARCHAR(50) NOT NULL
);

CREATE TABLE TIM(
	id INTEGER NOT NULL,
	naziv VARCHAR(100) NOT NULL,
	osnovan DATE NOT NULL,
	sediste VARCHAR(100) NOT NULL,
	liga INTEGER NOT NULL
);

CREATE TABLE NACIONALNOST(
	id INTEGER NOT NULL,
	naziv VARCHAR(100) NOT NULL,
	skracenica VARCHAR(50) NOT NULL
);

CREATE TABLE IGRAC(
	id INTEGER NOT NULL,
	ime VARCHAR(50) NOT NULL,
	prezime VARCHAR(50) NOT NULL,
	broj_reg VARCHAR(50) NOT NULL,
	datum_rodjenja DATE NOT NULL,
	nacionalnost INTEGER NOT NULL,
	tim INTEGER NOT NULL
);

ALTER TABLE LIGA ADD CONSTRAINT pk_LIGA
	PRIMARY KEY(id);

ALTER TABLE TIM ADD CONSTRAINT pk_TIM
	PRIMARY KEY(id);
	
ALTER TABLE NACIONALNOST ADD CONSTRAINT pk_NACIONALNOST
	PRIMARY KEY(id);	

ALTER TABLE IGRAC ADD CONSTRAINT pk_IGRAC
	PRIMARY KEY(id);

ALTER TABLE TIM ADD CONSTRAINT fk_TIM_LIGA
	FOREIGN KEY(LIGA) REFERENCES LIGA(id);

ALTER TABLE IGRAC ADD CONSTRAINT fk_IGRAC_NACIONALNOST
	FOREIGN KEY(NACIONALNOST) REFERENCES NACIONALNOST(id);
	
ALTER TABLE IGRAC ADD CONSTRAINT fk_IGRAC_TIM
	FOREIGN KEY(TIM) REFERENCES TIM(id);

CREATE INDEX idxfk_TIM_LIGA
	ON tim(LIGA);

CREATE INDEX idxfk_IGRAC_NACIONALNOST
	ON IGRAC(NACIONALNOST);
	
CREATE INDEX idxfk_IGRAC_TIM
	ON IGRAC(TIM);


CREATE SEQUENCE LIGA_SEQ
	INCREMENT 1;
	
CREATE SEQUENCE TIM_SEQ
	INCREMENT 1;
	
CREATE SEQUENCE NACIONALNOST_SEQ
	INCREMENT 1;
	
CREATE SEQUENCE IGRAC_SEQ
	INCREMENT 1;